[build]
  publish = "dist"
  command = "npm run build"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200